/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
    "./app/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#cbdde7",
        "on-surface": "#0d1e25",
        "secondary-container": "#90efef",
        "inverse-surface": "#23333a",
        "on-secondary-fixed": "#002020",
        surface: "#f4faff",
        "on-primary-container": "#8690ee",
        "on-tertiary-fixed": "#221b00",
        background: "#f4faff",
        "error-container": "#ffdad6",
        "primary-container": "#1a237e",
        "surface-container-high": "#d9ebf5",
        "inverse-on-surface": "#e2f3fd",
        "tertiary-container": "#c8a900",
        "on-secondary-container": "#006e6e",
        "inverse-primary": "#bdc2ff",
        "tertiary-fixed": "#ffe16d",
        secondary: "#006a6a",
        "on-primary-fixed": "#000767",
        "on-surface-variant": "#454652",
        "outline-variant": "#c6c5d4",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        tertiary: "#705d00",
        "tertiary-fixed-dim": "#e9c400",
        "on-tertiary-fixed-variant": "#544600",
        "surface-tint": "#4c56af",
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#004f4f",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "surface-variant": "#d4e5ef",
        outline: "#767683",
        "secondary-fixed": "#93f2f2",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#e0e0ff",
        "on-primary-fixed-variant": "#343d96",
        "secondary-fixed-dim": "#76d6d5",
        "on-secondary": "#ffffff",
        "on-background": "#0d1e25",
        primary: "#000666",
        "surface-container": "#dff1fb",
        "surface-container-highest": "#d4e5ef",
        "surface-container-low": "#e7f6ff",
        "on-tertiary-container": "#4b3e00",
        "primary-fixed-dim": "#bdc2ff",
        "surface-bright": "#f4faff",
        "on-secondary-container": "#006e6e",
      },
      fontFamily: {
        newsreader: ["Newsreader", "Georgia", "serif"],
        inter: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
